### ISSUE TITLE
trouble using matplotlib 

### ISSUE THREAD

**Issue by mackenziewillborn** [mackenziewillborn/bme547final#20]
I am having trouble using matplotlib on my Mac! I got it to work using venv instead of virtualenv for the ecg analysis project, but I can not seem to get that working again. Do you have any other advice? This is the website I am trying to follow. Thank you! 

[https://matplotlib.org/faq/osx_framework.html](url)

**Comment by dward2** [comment]
When you say that you cannot get it working again, whay is actually happening?   Are you getting an error?  If so, what does it say?  Is it working for your group mates?  Can you point me to the code that you are trying that is failing?

**Comment by mackenziewillborn** [comment]
This is the error I am receiving! 

ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.


It does work on my groupmates' computers, and right now I am simply importing it into our server code to display an image. I have already installed it in my virtualenv!

**Comment by dward2** [comment]
So, you are getting that error when trying to run `im_process_server.py`?

**Comment by dward2** [comment]
Also, do you still have the virtual environment you set up for your ECG project?  If so, go back to that virtual environment, and make sure your ECG project still works and displays plots.  Then, you could try running your server code in that virtual environment and see if matplotlib will import.  You will need to comment out imports that aren't installed in the ECG virtual environment, so the code will probably hit an error, but you can at least see if the matplotlib will import in the ECG virtual environment with your  new code.  This might give us a lead on what to do next.

**Comment by dward2** [comment]
Also, try the advice given by this website:

<https://markhneedham.com/blog/2018/05/04/python-runtime-error-osx-matplotlib-not-installed-as-framework-mac/>

**Comment by mackenziewillborn** [comment]
Thank you so much for your help! I ran it in my ECG environment, and also implemented what was suggested in the link you sent and that seemed to work. Thanks again!
