### ISSUE TITLE
Best way to send image info over to database

### ISSUE THREAD

**Issue by conjon1024** [mackenziewillborn/bme547final#22]
Hi Dr. Ward! I was wondering what data type is best for sending an image from the server to MongoDB. Currently, I am sending the raw and processed image over as a base64 string because I figured it would take up the least storage. However, the processed image seems to be taking more memory than I had expected. Is there anything wrong with my method? The link to my current server code should be located below. Please let me know if you have any issues opening it.

[https://github.com/mackenziewillborn/bme547final/blob/cmj39/proc_image_server/im_process_server.py](url)

**Comment by dward2** [comment]
A quick look at your code looks fine.  If your code is working and it is successfully storing the base 64 string, then I would say you are good to go.  Don't worry about the size of the image or base64 string too much.  Images files sometimes have very good compression.  And, the rough tools we are using to read in those image files and then converting to base 64 strings may not be optimized for space saving, as that is outside the scope for this assignment.

**Comment by conjon1024** [comment]
Thank you! If I run into any more issues with storage space I will let you know!
