### ISSUE TITLE
GUI Displaying information for multiple images

### ISSUE THREAD

**Issue by kelseyli143** [mackenziewillborn/bme547final#27]
When the user uploads multiple images for processing, I was wondering how the GUI is supposed to handle that in terms of displaying metadata? For example, should it display the image size for each individual image? For displaying the raw vs. processed image and the histograms, does this need to be done for each individual image as well?

**Comment by dward2** [comment]
You only need to display the meta data when showing an image in the GUI.  So, if you are uploading multiple files to the server, you don't need to display any or all of those files.  Or, if you choose to just show one of those file, show the meta data for that one file.  Uploading an image can be separated from then choosing an image to view.
