### ISSUE TITLE
Trouble displaying histogram equalized image in GUI

### ISSUE THREAD

**Issue by conjon1024** [mackenziewillborn/bme547final#28]
Hi Dr. Ward. I am having trouble displaying a processed image in the GUI after performing histogram equalization. I believe that the histogram equalization is being done correctly in the server (I check by using `plt.imsave('proc_test.jpg', img_proc)` and seeing what the processed image looks like), but for some reason, I am receiving a plain black image when I send it to the GUI. The other three processing methods are working properly, so I am confused about why this one is not. Is there something inherently different about the input/output data types used in the histogram equalization function?

In the server, this line in the function that encodes the processed image back into a b64 string seems to be where the function breaks:
```
pil_img = Image.fromarray(img_proc)
```

In the GUI, I have the following code where the b64 string is decoded and issues an error when the server breaks:
```
proc_image_bytes = base64.b64decode(proc_b64_string)
```

The GUI and server files are at [https://github.com/mackenziewillborn/bme547final/blob/cmj39/GET_proc_img/im_process_GUI.py](url)
[https://github.com/mackenziewillborn/bme547final/blob/cmj39/GET_proc_img/im_process_server.py](url)

**Comment by dward2** [comment]
That is a mystery.  I see the same behavior on my computer.  My advice:  don't worry about it for now.  Continue working on other parts of the project.  You have much more to gain by adding other functionality/documentation, etc. to your project than fixing this one little thing.  You are using the same code to return the processed image regardless of the processing method, and so I don't know why it would turn it black for only that method.  This won't be held against you.
