### ISSUE TITLE
VM Server down

### ISSUE THREAD

**Issue by dward2** [mackenziewillborn/bme547final#68]
@conjon1024 @mackenziewillborn @kelseyli143 I am unable to reach your server on your virtual machine.  Would you please verify that the virtual machine is on and that the server is active?  Thanks.

**Comment by conjon1024** [comment]
Hi Dr. Ward! It should be on now!

**Comment by dward2** [comment]
@conjon1024 @mackenziewillborn @kelseyli143 Thanks.  I see that it is.
